spring:
  batch:
    job:
      names: ${job.name:NONE}
      enabled: true
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create
#  sql:
#    init:
#      mode: always